# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Mar  4 10:27:44 2024
# ------------------------------------------------

package:
  name: micromamba
  version: 1.5.7
source:
  - folder: mamba
    patches:
      - 0001-Change-Windows-static-lib-name.patch
      - 0001-Compile-with-MD.patch
    sha256: bdc6d1d5ff8af77c5f12bbe79636cdc34f06dcf0694830a47a0c196833b8a186
    url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-1.5.7.tar.gz
build:
  ignore_run_exports_from:
    - fmt
    - libarchive-minimal-static
    - libcurl
    - libsolv
    - openssl
    - reproc-cpp
    - spdlog
  number: '0'
  string: '0'
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - c-ares 1.27.0 h10d778d_0
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_16
    - clang 16.0.6 hdae98eb_5
    - clang-16 16.0.6 default_h7151d67_5
    - clang_impl_osx-64 16.0.6 h8787910_10
    - clang_osx-64 16.0.6 hb91bd55_10
    - clangxx 16.0.6 default_h7151d67_5
    - clangxx_impl_osx-64 16.0.6 h6d92fbe_10
    - clangxx_osx-64 16.0.6 hb91bd55_10
    - cmake 3.28.3 h7c85d92_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 ha20a434_16
    - libclang-cpp16 16.0.6 default_h7151d67_5
    - libcurl 8.5.0 h726d00d_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.47.0 h67532ce_0
    - libxml2 2.12.5 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - ncurses 6.4 h93d8f39_2
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.2.1 hd75f5a5_0
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h10d778d_5
    - c-ares 1.27.0 h10d778d_0
    - c-ares-static 1.27.0 h10d778d_0
    - ca-certificates 2024.2.2 h8857fd0_0
    - cli11 2.4.1 h73e2aa4_0
    - cpp-expected 1.1.0 hb8565cd_0
    - fmt 10.2.1 h7728843_0
    - krb5 1.21.2 hb884880_0
    - krb5-static 1.21.2 hb884880_0
    - libarchive-minimal-static 3.7.2 h54d3e53_1
    - libcurl 8.5.0 h726d00d_0
    - libcurl-static 8.5.0 h726d00d_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libev-static 4.33 h10d778d_2
    - libiconv 1.17 hd75f5a5_2
    - libnghttp2 1.58.0 h64cf6d3_1
    - libnghttp2-static 1.58.0 hf822044_1
    - libopenssl-static 3.2.1 hd75f5a5_0
    - libsolv 0.7.28 h2d185b6_0
    - libsolv-static 0.7.28 h2d185b6_0
    - libssh2 1.11.0 hd019ec5_0
    - libssh2-static 1.11.0 hd019ec5_0
    - libzlib 1.2.13 h8a1eda9_5
    - lz4-c-static 1.9.4 h694c41f_0
    - ncurses 6.4 h93d8f39_2
    - nlohmann_json 3.11.2 hbbd2c75_0
    - openssl 3.2.1 hd75f5a5_0
    - reproc 14.2.4.post0 h10d778d_1
    - reproc-cpp 14.2.4.post0 h93d8f39_1
    - reproc-cpp-static 14.2.4 hf0c8a7f_0
    - reproc-static 14.2.4 hb7f2c08_0
    - spdlog 1.12.0 h8dd852c_2
    - xz 5.2.6 h775f41a_0
    - xz-static 5.2.6 h775f41a_0
    - yaml-cpp-static 0.8.0 he965462_0
    - zlib 1.2.13 h8a1eda9_5
    - zstd 1.5.5 h829000d_0
    - zstd-static 1.5.5 hf5e326d_0
  run:
    - libcxx >=16
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240304.3.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - mariusvniekerk
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/micromamba-feedstock
  sha: 310146603937a68dcd999975e34f6aaec13237aa
